spring:
  application:
    name: notification-service

  rabbitmq:
    host: localhost
    port: 5673
    username: admin
    password: admin
    listener:
      simple:
        default-requeue-rejected: false

server:
  port: 8084

logging:
  level:
    org.springframework.amqp: INFO
    com.deliveryapp.notificationservice: INFO
