services:
  postgres-order:
    image: postgres:16-alpine
    container_name: delivery-postgres-order
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: order_pass
    volumes:
      - postgres_order_data:/var/lib/postgresql/data

  postgres-courier:
    image: postgres:16-alpine
    container_name: delivery-postgres-courier
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: courier_db
      POSTGRES_USER: courier_user
      POSTGRES_PASSWORD: courier_pass
    volumes:
      - postgres_courier_data:/var/lib/postgresql/data

volumes:
  postgres_order_data:
  postgres_courier_data: