spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:postgresql://localhost:5435/payment_db
    username: payment_user
    password: payment_pass
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    host: localhost
    port: 5673
    username: admin
    password: admin
    listener:
      simple:
        default-requeue-rejected: false

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    open-in-view: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

server:
  port: 8083

logging:
  level:
    org.springframework.amqp: INFO
    org.hibernate.SQL: DEBUG
