spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5433/order_db
    username: order_user
    password: order_pass
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    host: localhost
    port: 5673
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    open-in-view: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

server:
  port: 8081

courier-service:
  url: http://localhost:8082

logging:
  level:
    org.springframework.amqp: INFO
    org.hibernate.SQL: DEBUG